name: carla0910
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==0.15.0
    - astunparse==1.6.3
    - backcall==0.2.0
    - cachetools==5.5.0
    - cffi==1.15.1
    - charset-normalizer==3.4.0
    - cloudpickle==2.2.1
    - cycler==0.11.0
    - decorator==5.1.1
    - dm-tree==0.1.8
    - easydict==1.13
    - flatbuffers==1.12
    - fonttools==4.38.0
    - gast==0.3.3
    - google-auth==2.36.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - gym==0.23.0
    - gym-notices==0.0.8
    - h5py==2.10.0
    - idna==3.10
    - importlib-metadata==6.7.0
    - ipdb==0.13.13
    - ipython==7.34.0
    - jedi==0.19.2
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.5
    - markdown==3.4.4
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - networkx==2.6.3
    - numpy==1.19.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - opencv-python==4.10.0.84
    - opt-einsum==3.3.0
    - packaging==24.0
    - pandas==1.3.5
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - prompt-toolkit==3.0.48
    - protobuf==3.20.3
    - ptyprocess==0.7.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pygame==2.6.1
    - pygments==2.17.2
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - scipy==1.7.3
    - six==1.15.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - tensorflow-probability==0.11.1
    - termcolor==1.1.0
    - tomli==2.0.1
    - torch==1.13.1
    - torchgen==0.0.1
    - traitlets==5.9.0
    - typing-extensions==3.7.4.3
    - urllib3==2.0.7
    - wcwidth==0.2.13
    - werkzeug==2.2.3
    - wrapt==1.12.1
    - zipp==3.15.0
prefix: /root/miniconda3/envs/carla0910
